# docker-compose build --progress=plain
# docker-compose up -d
# curl -I http://localhost:8080
# google-chrome --incognito http://localhost:8080
# docker-compose down
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_image
    environment:
      - TZ=America/Sao_Paulo
    network_mode: bridge
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 256M
        reservations:
          memory: 256M
    restart: 'no'
    healthcheck:
      #disable: true
      test: 'curl -fsSLI http://localhost:8080/index.html -o /dev/null -w "%{http_code}" -H "User-Agent: HealthCheck"'
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
